### ISSUE TITLE
Nice Work, questions about the soft

### ISSUE THREAD

**Issue by hmyh1202** [ZhouQiangwei/BSsnpcall#1]
Hi, Qiangwei:
    
    I have some questions for you work.
    What is the version of the Bis-SNP that you have had test ? 
    How to adjust the adjust the parameters and filter out high quality and accurate SNP sites ?
    And did  you verify the SNP sites by other means ?
thank you.

The best !

**Comment by ZhouQiangwei** [comment]
Hi,

We use the bissnp-1.0.0.jar, cause this is the work of the previous two years. The project has been suspended for some personal reason. We will restart the project ASAP, finish the test and subsequent functions, and test with the new software version and comparative standards.

Best regards

**Comment by hmyh1202** [comment]
Ok， good luck !
